### ISSUE TITLE
Aggregates not automatically saving

### ISSUE THREAD

**Issue by iainmckay** [prooph/event-sourcing#59]
I've followed the example in the quickstart on the latest 5.0.0 beta. The comments say that an aggregate loaded from a repository will automatically commit their events. I cannot get this behaviour without calling `saveAggregateRoot`.

I'm using Postgres and have configured the event store, transaction manager and service bus. Everything works except the automatic committing.

Perhaps I'm missing something?

**Comment by prolic** [comment]
With the new version there is no automatic saving anymore. Thanks for
pointing this out, we need to update the example.

Am 24.03.2017 19:43 schrieb "Iain Mckay" <notifications@github.com>:

I've followed the example in the quickstart on the latest 5.0.0 beta. The
comments say that an aggregate loaded from a repository will automatically
commit their events. I cannot get this behaviour without calling
saveAggregateRoot.

I'm using Postgres and have configured the event store, transaction manager
and service bus. Everything works except the automatic committing.

Perhaps I'm missing something?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/prooph/event-sourcing/issues/59>, or mute the thread

**Comment by iainmckay** [comment]
Ah, that's unfortunate.

Is this by design or will it make an appearance at some point?

**Comment by iainmckay** [comment]
Great, thanks :)
